services:
  postgres:
    image: postgres:15
    container_name: pool_postgres
    environment:
      POSTGRES_DB: pool
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pool-network

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: pool_backend
#    ports:
#      - "${APP_PORT}:8080"
#    depends_on:
#      - postgres
#    networks:
#      - pool-network

volumes:
  postgres_data:

networks:
  pool-network: